<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net35</TargetFramework>
    <LangVersion>latest</LangVersion>
    <AutomaticallyUseReferenceAssemblyPackages>false</AutomaticallyUseReferenceAssemblyPackages>
    <GameDir Condition="'$(GameDir)' == '' and '$(GEKIDRIVE_GAME_DIR)' != ''">$(GEKIDRIVE_GAME_DIR)</GameDir>
    <GameDir Condition="'$(GameDir)' == ''">$(MSBuildThisFileDirectory)..\..\GameFiles\package</GameDir>
    <FrameworkPathOverride>$(GameDir)\mu3_Data\Managed</FrameworkPathOverride>
    <OutputPath>../../artifacts/</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <AssemblyName>GekiDrive.Public</AssemblyName>
    <Version>0.5.1</Version>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="overlay.html" LogicalName="GekiDrive.overlay.html" />
    <Reference Remove="System.Data;System.Drawing;System.Runtime.Serialization;System.Xml.Linq" />
    <Reference Include="BepInEx"><HintPath>$(GameDir)/BepInEx/core/BepInEx.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="0Harmony"><HintPath>$(GameDir)/BepInEx/core/0Harmony.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine"><HintPath>$(GameDir)/mu3_Data/Managed/UnityEngine.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Assembly-CSharp"><HintPath>$(GameDir)/mu3_Data/Managed/Assembly-CSharp.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Assembly-CSharp-firstpass"><HintPath>$(GameDir)/mu3_Data/Managed/Assembly-CSharp-firstpass.dll</HintPath><Private>false</Private></Reference>
  </ItemGroup>
  <Target Name="RemoveUnusedFrameworkReferences" BeforeTargets="ResolveAssemblyReferences"><ItemGroup><Reference Remove="System.Data;System.Drawing;System.Runtime.Serialization;System.Xml.Linq" /></ItemGroup></Target>
</Project>




